name: nextcloud-base-apache

services:
  lool:
    image: libreoffice/online:master
    container_name: lool
    environment:
      TZ: ${TZ}
      domain: ${HOST_IP}
      username: ${LOOL_USERNAME}
      password: ${LOOL_PASSWORD}
      extra_params: ${LOOL_EXTRA_PARAMS}
      DONT_GEN_SSL_CERT: 1
    cap_add:
      - MKNOD
    ports:
      - ${LOOL_HOST_PORT}:${LOOL_DOCKER_CONTAINER_PORT}
    volumes:
      - loolwsd:/etc/loolwsd
    networks: 
      - nextcloud

  mariadb:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - ${DB_HOST_PORT}:${DB_DOCKER_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - ${NEXTCLOUD_HOST_PORT}:${NEXTCLOUD_DOCKER_CONTAINER_PORT}
    environment:
      TZ: ${TZ}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    depends_on:
      - mariadb
    networks: 
      - nextcloud

volumes:
  loolwsd: {}
  mysql: {}
  nextcloud: {}

networks:
  nextcloud:
    external: true
